version: '2.1'

services:
  uptimerobot_exporter:
    build: .
    restart: unless-stopped
    net: host
    environment:
      UPTIMEROBOT_API_KEY: ur1642717-bd88b7720c797d0555232776
    ports:
      - 9705:9705
    read_only: true
