{
 "title": "UptimeRobot [MAIN]",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Down Monitors",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uptimerobot_accountdetails{down_monitors!=\"0\"}",
     "source": "url",
     "type": "json",
     "url": "https://jsonplaceholder.typicode.com/users",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Up Monitors",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uptimerobot_accountdetails",
     "legendFormat": "__auto",
     "source": "url",
     "type": "json",
     "url": "https://jsonplaceholder.typicode.com/users",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Paused Monitors",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uptimerobot_accountdetails",
     "legendFormat": "__auto",
     "source": "url",
     "type": "json",
     "url": "https://jsonplaceholder.typicode.com/users",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Down Services",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sort(uptimerobot_status)" }
   ]
  },
  {
   "title": "Running Services",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sort(uptimerobot_status)" }
   ]
  },
  {
   "title": "Monitors Response time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "uptimerobot_response_time", "legendFormat": "{{ name }}" }
   ]
  }
 ]
}